/cameraDA3302323/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA2584810/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA2419544/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA5796927/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA5796907/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA5796923/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
/cameraDA5796903/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 24000
    gain: 32.0
